[project]
name = "login"
version = "0.1.0"
description = "Login and Signup application with MySQL"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.0.0",
    "mysql>=0.0.3",
    "mysql-connector-python==8.2.0",
    "werkzeug==3.0.1",
]
